version: '3.8'

services:
  backend:
    image: ghcr.io/${REPO_LC}/agriplan-backend:latest
    container_name: agriplan-backend
    restart: always
    ports:
      - "127.0.0.1:3284:3284"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - frontend

  frontend:
    image: ghcr.io/${REPO_LC}/agriplan-frontend:latest
    container_name: agriplan-frontend
    restart: always
    ports:
      - "127.0.0.1:3285:3285"
    env_file:
      - .env

networks:
  default:
    name: agriplan_default
    external: true
