import nativeConfig from '../../shared/native-config.json';
import { Capacitor } from '@capacitor/core';
import { startAuthentication, startRegistration } from '@simplewebauthn/browser';
import { meta, setMeta, importGuest } from './db';
import type { SessionUser } from './types';
export const API_BASE = Capacitor.isNativePlatform() ? 'https://egin.perricheno.com' : '';
export async function api<T = any>(path:string,body?:unknown,method=body===undefined?'GET':'POST'):Promise<T>{const r=await fetch(API_BASE+'/api'+path,{method,credentials:'include',headers:{'Content-Type':'application/json','X-EGIN':'1'},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(20000)});let data;try{data=await r.json();}catch{throw new Error('Сервер недоступен. Повторите позже.');}if(!r.ok)throw Object.assign(new Error(data.error||'Запрос не выполнен'),{status:r.status});return data;}
export async function remember(user:SessionUser){await setMeta('user',user);await setMeta('owner',user.id);await setMeta('apiBase',API_BASE);}
async function nativePasskey(){if(Capacitor.getPlatform()==='ios'&&!nativeConfig.iosPasskeyReady)throw new Error('В этой сборке iOS используйте passkey в веб-версии EGIN.');const {CapacitorPasskey}=await import('@capgo/capacitor-passkey');if(!(await CapacitorPasskey.isSupported()).available)throw new Error('Это устройство не поддерживает passkey. Используйте код восстановления или другое устройство.');return CapacitorPasskey;}
export async function register(name:string,authenticator:'platform'|'securityKey'='platform'){const flow=await api('/auth/register/options',{name,authenticator});const response=Capacitor.isNativePlatform()?await (await nativePasskey()).createCredential({origin:'https://egin.perricheno.com',publicKey:flow.options}):await startRegistration({optionsJSON:flow.options});const result=await api('/auth/register/verify',{flow:flow.flow,response});const guest=await meta('owner','guest')==='guest';await remember(result.user);if(guest)await importGuest();return result as {user:SessionUser;recovery:string|null};}
export async function authenticate(options:any){return Capacitor.isNativePlatform()?await (await nativePasskey()).getCredential({origin:'https://egin.perricheno.com',publicKey:options}):await startAuthentication({optionsJSON:options});}
export async function login(){const flow=await api('/auth/login/options',{});const response=await authenticate(flow.options);const result=await api('/auth/login/verify',{flow:flow.flow,response});await remember(result.user);return result;}
export async function recover(code:string){const result=await api('/auth/recover',{code});await remember(result.user);return result;}
export async function logout(){await api('/logout',{});await setMeta('owner','guest');await setMeta('user',null);}
export function humanError(e:unknown){if(e instanceof Error){if(e.name==='NotAllowedError'||e.name==='AbortError')return 'Действие отменено или истекло время ожидания. Можно повторить.';if(e.name==='NotFoundError')return 'Камера или микрофон не найдены.';if(e.name==='NotReadableError')return 'Камера или микрофон заняты другим приложением.';if(e.message==='Failed to fetch')return 'Нет связи с сервером. Данные остаются на телефоне.';return e.message;}return 'Не удалось выполнить действие';}
