import { useEffect,useId,useMemo,useRef,useState } from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import { useRows,useMeta } from '../../entities/workspace/hooks';
import { save,remove,setMeta,owner as getOwner } from '../../entities/workspace/db';
import type { Field,Row } from '../../entities/workspace/types';
import { parseLandGeoJSON,measureBoundary,DEMO_PARCELS,type Parcel } from '../../entities/workspace/land';
import { api,humanError } from '../../entities/workspace/api';
import { Sheet } from '../../shared/ui/Sheet';
import { Icon } from '../../shared/ui/Icon';
import { Page,Notice } from './ui';
import './fields.css';
type CadastralParcel=Parcel&{region?:string;district?:string;registeredAreaHa?:number};
type MapDistrict={id:number;srid:number};
type MapFocus={latitude:number;longitude:number;zoom:number;revision:number};
const CADASTRE_URL='https://map.gov4c.kz/egkn/';
const areaLabel=(area:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(area);
const cropNames:Record<Field['crop'],string>={unknown:'Культура не указана',wheat:'Пшеница',tomato:'Томаты',apple:'Яблоня',sunflower:'Подсолнечник'};
function previewRow(data:Field,id='preview'):Row<Field>{return {id,key:id,owner:'guest',kind:'field',data,version:0,deleted:false,dirty:false,localRevision:0,updated:''};}
function sourceLabel(data:Field){return data.cadastre?.source==='demo'?'Демонстрационный контур':data.cadastre?.source==='public-map'?'Публичная карта ЕГКН':data.cadastre?.source==='geojson'?'Импорт GeoJSON':data.boundary?'Контур пользователя':'Точка без границ';}
export function FieldMap({fields,selected,onSelect,onPoint,onZoom,focus,district,wide=false}:{fields:Row<Field>[];selected?:string;onSelect?:(id:string)=>void;onPoint?:(lat:number,lon:number,zoom:number)=>void;onZoom?:(zoom:number)=>void;focus?:MapFocus;district?:MapDistrict;wide?:boolean}){
  const host=useRef<HTMLDivElement>(null),map=useRef<L.Map|null>(null),layer=useRef<L.LayerGroup|null>(null),lastView=useRef(''),callbacks=useRef({onPoint,onSelect,onZoom});callbacks.current={onPoint,onSelect,onZoom};const [error,setError]=useState(''),[overlayError,setOverlayError]=useState('');
  useEffect(()=>{const m=L.map(host.current!,{zoomControl:false,scrollWheelZoom:wide,zoomAnimation:false,fadeAnimation:false,markerZoomAnimation:false}).setView(wide?[48.4,67.5]:[51.1694,71.4491],wide?5:10);map.current=m;L.control.zoom({position:wide?'topright':'bottomright'}).addTo(m);const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap</a>',maxZoom:19}).addTo(m);tiles.on('tileerror',()=>setError('Подложка карты недоступна. Сохранённые границы и данные остаются доступны.'));layer.current=L.layerGroup().addTo(m);m.on('click',(e:L.LeafletMouseEvent)=>callbacks.current.onPoint?.(e.latlng.lat,e.latlng.lng,m.getZoom()));m.on('zoomend',()=>callbacks.current.onZoom?.(m.getZoom()));const resize=new ResizeObserver(()=>m.invalidateSize({animate:false}));resize.observe(host.current!);return()=>{resize.disconnect();m.stop();m.remove();map.current=null;};},[]);
  useEffect(()=>{const m=map.current,g=layer.current;if(!m||!g)return;g.clearLayers();const bounds=L.latLngBounds([]);for(const f of fields){const active=f.id===selected;let shape:L.Path;if(f.data.boundary){const coords=f.data.boundary.coordinates.map(r=>r.map(p=>L.latLng(p[1],p[0])));shape=L.polygon(coords,{color:'#214d36',fillColor:'#214d36',fillOpacity:active ? .28 : .1,weight:active?3:1.5,dashArray:f.data.cadastre?.source==='demo'?'6 5':undefined,bubblingMouseEvents:false}).addTo(g);for(const p of coords[0])bounds.extend(p);}else{shape=L.circleMarker([f.data.latitude,f.data.longitude],{radius:active?10:7,color:'#214d36',fillColor:active?'#214d36':'#ffffff',fillOpacity:1,weight:2,bubblingMouseEvents:false}).addTo(g);bounds.extend([f.data.latitude,f.data.longitude]);}const label=document.createElement('span');label.textContent=f.data.name;shape.bindTooltip(label);shape.on('click',()=>callbacks.current.onSelect?.(f.id));}
    const chosen=fields.find(f=>f.id===selected);const key=JSON.stringify([selected,fields.map(f=>[f.id,f.data.latitude,f.data.longitude,f.data.boundary])]);if(key!==lastView.current){lastView.current=key;if(chosen?.data.boundary)m.fitBounds(L.latLngBounds(chosen.data.boundary.coordinates[0].map(p=>L.latLng(p[1],p[0]))),{padding:[24,24],maxZoom:wide?18:19,animate:false});else if(chosen)m.setView([chosen.data.latitude,chosen.data.longitude],14,{animate:false});else if(bounds.isValid())m.fitBounds(bounds,{padding:[28,28],maxZoom:15,animate:false});}
  },[fields,selected]);
  useEffect(()=>{if(focus)map.current?.setView([focus.latitude,focus.longitude],focus.zoom,{animate:false});},[focus]);
  useEffect(()=>{const m=map.current;setOverlayError('');if(!m||!district)return;const overlay=L.tileLayer(`/api/cadastre/tiles/{z}/{x}/{y}.png?district=${district.id}&srid=${district.srid}`,{minZoom:14,maxZoom:19,opacity:.65,attribution:'Границы © ЕГКН',keepBuffer:1}).addTo(m);overlay.on('tileerror',()=>setOverlayError('Кадастровый слой недоступен. Поиск по номеру и выбор участка касанием остаются доступны.'));return()=>{overlay.remove();};},[district]);
  useEffect(()=>{
    const m=map.current;if(!m||!wide||!district)return;
    const labels=L.layerGroup().addTo(m);let generation=0,disposed=false,inFlight=false,pending=false,moving=false,timer:ReturnType<typeof setTimeout>|undefined;
    async function refresh(){
      if(disposed||moving)return;if(inFlight){pending=true;return;}
      const zoom=m!.getZoom(),bounds=m!.getBounds();
      if(zoom<17||zoom>19||bounds.getEast()-bounds.getWest()>.025||bounds.getNorth()-bounds.getSouth()>.025)return;
      const request=generation;inFlight=true;pending=false;
      const query=new URLSearchParams({district:String(district!.id),zoom:String(zoom),west:bounds.getWest().toFixed(8),south:bounds.getSouth().toFixed(8),east:bounds.getEast().toFixed(8),north:bounds.getNorth().toFixed(8)});
      try{
        const result=await api<{labels:{number:string;latitude:number;longitude:number}[]}>(`/cadastre/labels?${query}`,undefined,'GET');
        if(disposed||request!==generation)return;
        const placed:L.Point[]=[];
        for(const item of result.labels.slice(0,150)){
          if(typeof item.number!=='string'||!Number.isFinite(item.latitude)||!Number.isFinite(item.longitude)||!bounds.contains([item.latitude,item.longitude]))continue;
          const point=m!.latLngToContainerPoint([item.latitude,item.longitude]);if(placed.some(p=>Math.abs(p.x-point.x)<76&&Math.abs(p.y-point.y)<18))continue;placed.push(point);
          const text=document.createElement('span');text.textContent=item.number;
          L.marker([item.latitude,item.longitude],{icon:L.divIcon({className:'land-parcel-label',html:text,iconSize:[0,0]}),interactive:false,keyboard:false}).addTo(labels);
        }
      }catch{/* Labels are optional; parcel lookup and outlines remain usable. */}
      finally{inFlight=false;if(!disposed&&!moving&&(pending||request!==generation)){clearTimeout(timer);timer=setTimeout(()=>void refresh(),400);}}
    }
    function invalidate(){generation++;labels.clearLayers();clearTimeout(timer);}
    function startMove(){moving=true;invalidate();}
    function schedule(){moving=false;invalidate();timer=setTimeout(()=>void refresh(),400);}
    m.on('movestart zoomstart',startMove);m.on('moveend zoomend resize',schedule);schedule();
    return()=>{disposed=true;generation++;clearTimeout(timer);m.off('movestart zoomstart',startMove);m.off('moveend zoomend resize',schedule);labels.remove();};
  },[district,wide]);
  return <><div className="field-map" ref={host} role="region" aria-label="Карта участков и границ"/><Notice>{error||overlayError}</Notice></>;
}
function useWorkspaceGuard(expectedOwner:string){const active=useRef(true);useEffect(()=>{active.current=true;return()=>{active.current=false;};},[]);return async()=>{const currentOwner=await getOwner();if(!active.current||currentOwner!==expectedOwner)throw new Error('Профиль изменился. Откройте участок заново.');};}
function saveForOwner(data:Field,existing:Row<Field>|undefined,expectedOwner:string){const draft=existing||{...previewRow(data,crypto.randomUUID()),owner:expectedOwner};return save('field',data,draft);}
export default function FieldsPage(){const workspaceOwner=useMeta('owner','guest');return <FieldsContent key={workspaceOwner} workspaceOwner={workspaceOwner}/>;}
function FieldsContent({workspaceOwner}:{workspaceOwner:string}){
  const {rows,error}=useRows<Field>('field'),selected=useMeta('selectedField','');const [editing,setEditing]=useState<Row<Field>|'new'|null>(null),[adding,setAdding]=useState<{existing?:Row<Field>}|null>(null),[notice,setNotice]=useState('');const current=rows.find(f=>f.id===selected)||rows[0];const realFields=rows.filter(f=>f.data.cadastre?.source!=='demo'),demoCount=rows.length-realFields.length;const assertCurrent=useWorkspaceGuard(workspaceOwner);
  async function select(id:string){try{await assertCurrent();await setMeta('selectedField',id);}catch(e){setNotice(humanError(e));}}
  return <Page title="Участки" back="/" action={<button className="icon-button" aria-label="Добавить участок" onClick={()=>setAdding({})}><Icon name="plus"/></button>}>
    <div className="land-intro"><span className="land-eyebrow">Земля вашего хозяйства</span><p>Границы объединяют погоду, датчики и события на одном участке.</p></div>
    <div className="land-map-wrap"><FieldMap fields={rows} selected={current?.id} onSelect={id=>void select(id)}/><span className="land-map-caption"><Icon name="layers" size={15}/>{rows.length?`${realFields.length} участков · ${areaLabel(realFields.reduce((n,f)=>n+f.data.area,0))} га${demoCount?` · демо: ${demoCount}`:''}`:'Добавьте первый контур'}</span></div>
    <Notice error>{error||notice}</Notice>
    {!rows.length?<section className="land-onboarding"><h2>Начните с границ</h2><p>Найдите участок по кадастровому номеру или загрузите его границы. Перед добавлением проверьте контур на карте.</p><button className="primary-button" onClick={()=>setAdding({})}><Icon name="plus" size={18}/>Добавить участок</button><p className="form-help">Контуры и карточки сохраняются на устройстве и доступны без сети. Для синхронизации нужен вход.</p></section>:<>
      <div className="land-switcher" aria-label="Выбор участка">{rows.map(f=><button key={f.id} className={f.id===current?.id?'is-selected':''} aria-pressed={f.id===current?.id} onClick={()=>void select(f.id)}>{f.data.name}{f.data.cadastre?.source==='demo'&&<small>Демо</small>}</button>)}</div>
      {current&&<article className="land-detail"><div className="section-head"><div><span className="land-eyebrow">{sourceLabel(current.data)}</span><h2>{current.data.name}</h2></div><button className="icon-button" aria-label="Настройки участка" onClick={()=>setEditing(current)}><Icon name="settings"/></button></div><div className="land-facts"><div><small>{current.data.boundary?'Площадь по контуру':'Указанная площадь'}</small><strong>{areaLabel(current.data.area)} <span>га</span></strong></div><div><small>Границы</small><strong>{current.data.boundary?'Загружены':'Не заданы'}</strong></div></div><dl className="land-meta"><div><dt>Кадастровый номер</dt><dd>{current.data.cadastre?.number||'Не указан'}</dd></div><div><dt>Культура</dt><dd>{cropNames[current.data.crop]}</dd></div>{current.data.cadastre?.importedAt&&<div><dt>Контур добавлен</dt><dd>{new Date(current.data.cadastre.importedAt).toLocaleDateString('ru-RU')}</dd></div>}<div><dt>Координаты центра</dt><dd>{current.data.latitude.toFixed(5)}, {current.data.longitude.toFixed(5)}</dd></div></dl>{current.data.cadastre?.source==='demo'?<Notice>Учебный контур EGIN. Он не получен из кадастра и не обозначает вашу собственность.</Notice>:current.data.cadastre?.number?<p className="form-help">{current.data.cadastre?.source==='public-map'?'Границы получены с публичной карты ЕГКН. Права на землю не проверены.':'Номер указан пользователем или взят из файла. Права на землю и соответствие контура кадастру не проверены.'}</p>:null}{current.data.boundary?<button className="secondary-button" onClick={()=>downloadBoundary(current.data)}><Icon name="share" size={18}/>Скачать контур GeoJSON</button>:<button className="secondary-button" onClick={()=>setAdding({existing:current})}><Icon name="layers" size={18}/>Добавить границы</button>}<a className="land-events-link" href="#/events"><Icon name="bell" size={18}/>Открыть центр событий<Icon name="right" size={16}/></a></article>}
      <button className="secondary-button" onClick={()=>setAdding({})}><Icon name="plus" size={18}/>Добавить ещё участок</button>
    </>}
    <OfficialCadastre/>
    {adding&&<AcquireField workspaceOwner={workspaceOwner} existing={adding.existing} fields={rows} onClose={()=>setAdding(null)} onPoint={()=>{setAdding(null);setEditing('new');}}/>}
    {editing&&<FieldEditor workspaceOwner={workspaceOwner} existing={editing==='new'?undefined:editing} onClose={()=>setEditing(null)}/>}
  </Page>;
}
function OfficialCadastre(){return <div className="land-official"><div><Icon name="map" size={23}/><h2>Источник — публичная карта ЕГКН</h2></div><p>Выбирайте землю на карте EGIN или находите её по кадастровому номеру. Сведения о границах не подтверждают право собственности.</p><a className="secondary-button" href={CADASTRE_URL} target="_blank" rel="noopener noreferrer">Официальная карта ЕГКН<Icon name="arrow" size={17}/></a></div>;}
function downloadBoundary(data:Field){const payload={type:'Feature',properties:{name:data.name,...(data.cadastre?.number?{cadastral_number:data.cadastre.number}:{}),source:data.cadastre?.source||'user',...(data.cadastre?.source==='demo'?{description:'Synthetic EGIN demonstration polygon. Not cadastral data.'}:{})},geometry:data.boundary};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/geo+json'}));const a=document.createElement('a');a.href=url;a.download='egin-parcel.geojson';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function AcquireField({workspaceOwner,existing,fields,onClose,onPoint}:{workspaceOwner:string;existing?:Row<Field>;fields:Row<Field>[];onClose:()=>void;onPoint:()=>void}){
  const assertCurrent=useWorkspaceGuard(workspaceOwner),dialog=useRef<HTMLDialogElement>(null),titleId=useId(),requestId=useRef(0);
  const [parcels,setParcels]=useState<CadastralParcel[]>([]),[selection,setSelection]=useState<number|null>(null),[source,setSource]=useState<'geojson'|'demo'|'public-map'>('public-map'),[name,setName]=useState(''),[number,setNumber]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[mode,setMode]=useState<'number'|'map'>('number'),[toolsOpen,setToolsOpen]=useState(false),[detailsOpen,setDetailsOpen]=useState(false),[message,setMessage]=useState(''),[zoom,setZoom]=useState(5),[focus,setFocus]=useState<MapFocus|undefined>(()=>{const field=existing||fields[0];return field?{latitude:field.data.latitude,longitude:field.data.longitude,zoom:14,revision:0}:undefined;}),[district,setDistrict]=useState<MapDistrict>();
  const signedIn=useMeta<{id:string}|null>('user',null),[searchNumber,setSearchNumber]=useState(existing?.data.cadastre?.number||'');
  useEffect(()=>{const d=dialog.current!,previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;document.body.style.overflow='hidden';d.showModal();const resize=()=>{if(window.visualViewport)d.style.height=`${window.visualViewport.height}px`;};resize();window.visualViewport?.addEventListener('resize',resize);return()=>{requestId.current++;d.close();document.body.style.overflow=overflow;window.visualViewport?.removeEventListener('resize',resize);previous?.focus();};},[]);
  const selected=selection===null?undefined:parcels[selection],effectiveSource=selected?.demo?'demo':source;
  const duplicate=selected&&fields.find(f=>f.id!==existing?.id&&(JSON.stringify(f.data.boundary)===JSON.stringify(selected.boundary)||(effectiveSource!=='demo'&&number.trim()&&f.data.cadastre?.number?.trim()===number.trim())));
  const mapRows=useMemo(()=>parcels.map((p,i)=>previewRow({...p,crop:'unknown',cadastre:{source:p.demo?'demo':source,importedAt:new Date().toISOString()}},String(i))),[parcels,source]);
  function choose(i:number){setSelection(i);setName(existing?.data.name||parcels[i].name);setNumber(source==='demo'||parcels[i].demo?'':parcels[i].number||existing?.data.cadastre?.number||'');setDetailsOpen(false);}
  function reset(){setSelection(null);setParcels([]);setDetailsOpen(false);setError('');setMessage('');}
  async function find(path:string,point=false){const request=++requestId.current;setBusy(true);reset();setToolsOpen(false);try{await assertCurrent();const response=await api<{mapDistrict?:MapDistrict;candidates:{cadastralNumber:string;region:string;district:string;boundary:unknown;registeredAreaHa?:number}[]}>(path,undefined,'GET',45000);await assertCurrent();if(request!==requestId.current)return;setDistrict(response.mapDistrict);const found=response.candidates.map(p=>({...measureBoundary(p.boundary),number:p.cadastralNumber,name:existing?.data.name||`Участок ${p.cadastralNumber}`,region:p.region,district:p.district,registeredAreaHa:p.registeredAreaHa}));setParcels(found);setSource('public-map');setMessage(found.length?'':point?'В этой точке участок не найден. Коснитесь соседнего места или найдите по номеру.':'Участок не найден. Проверьте кадастровый номер или загрузите файл границ.');if(found.length===1){setSelection(0);setName(found[0].name);setNumber(found[0].number);}}catch(e){if(request===requestId.current)setError((e as {status?:number}).status===401?'Для поиска в ЕГКН войдите в EGIN. Файл границ и демо доступны без входа.':humanError(e));}finally{if(request===requestId.current)setBusy(false);}}
  function search(){(document.activeElement as HTMLElement)?.blur();void find('/cadastre/search?number='+encodeURIComponent(searchNumber.trim()));}
  function mapPoint(latitude:number,longitude:number,mapZoom:number){if(busy||toolsOpen||(parcels.length>0&&source!=='public-map'))return;setMode('map');if(mapZoom<15){setFocus({latitude,longitude,zoom:Math.min(15,mapZoom+3),revision:Date.now()});setMessage('Приблизьте нужное место и коснитесь земли, чтобы выбрать участок.');return;}void find(`/cadastre/identify?latitude=${latitude.toFixed(8)}&longitude=${longitude.toFixed(8)}`,true);}
  async function locate(){setError('');setBusy(true);try{if(!navigator.geolocation)throw new Error('Геолокация недоступна');const position=await new Promise<GeolocationPosition>((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:15000,maximumAge:60000}));await assertCurrent();setFocus({latitude:position.coords.latitude,longitude:position.coords.longitude,zoom:16,revision:Date.now()});setMode('map');setMessage('Коснитесь нужного участка. Ваше местоположение не определяет границы земли.');}catch{setError('Не удалось определить местоположение. Разрешите геолокацию или найдите место вручную.');}finally{setBusy(false);}}
  async function load(file:File){setBusy(true);reset();setSource('geojson');try{if(file.size>2*1024*1024)throw new Error('Файл слишком большой. Максимум — 2 МБ.');const text=await file.text();await assertCurrent();const parsed=parseLandGeoJSON(text);setParcels(parsed);setSelection(parsed.length===1?0:null);setName(existing?.data.name||parsed[0].name);setNumber(parsed[0].number||existing?.data.cadastre?.number||'');setToolsOpen(false);}catch(e){setError(humanError(e));}finally{setBusy(false);}}
  async function submit(){if(!selected||duplicate)return;setBusy(true);setError('');try{if(/[\u0000-\u001f\u007f]/.test(number))throw new Error('В кадастровом номере есть недопустимые символы.');await assertCurrent();const row=await saveForOwner({name:name.trim(),boundary:selected.boundary,latitude:selected.latitude,longitude:selected.longitude,area:selected.area,crop:existing?.data.crop||'unknown',cadastre:{source:effectiveSource,...(effectiveSource!=='demo'&&number.trim()?{number:number.trim()}:{}),importedAt:new Date().toISOString()}},existing,workspaceOwner);await assertCurrent();await setMeta('selectedField',row.id);onClose();}catch(e){setError(humanError(e));}finally{setBusy(false);}}
  return <dialog ref={dialog} className="land-picker" aria-labelledby={titleId} onCancel={e=>{e.preventDefault();onClose();}}>
    <header className="land-picker-header"><button className="icon-button" aria-label="Закрыть выбор участка" onClick={onClose}><Icon name="back"/></button><div><h2 id={titleId}>{existing?'Границы участка':'Добавить участок'}</h2><small>Кадастровая карта Казахстана</small></div><button className={`icon-button ${toolsOpen?'is-active':''}`} aria-label="Другие способы добавления" aria-expanded={toolsOpen} onClick={()=>setToolsOpen(!toolsOpen)}><Icon name="layers"/></button></header>
    <div className="land-picker-search"><div className="land-picker-tabs" role="tablist" aria-label="Способ поиска"><button role="tab" aria-selected={mode==='number'} onClick={()=>{setMode('number');setToolsOpen(false);}}>По номеру</button><button role="tab" aria-selected={mode==='map'} onClick={()=>{setMode('map');setToolsOpen(false);}}>На карте</button></div><form onSubmit={e=>{e.preventDefault();if(searchNumber.trim()&&!busy)search();}}><label className="land-search-input"><span className="sr-only">Кадастровый номер</span><input type="search" inputMode="text" enterKeyHint="search" value={searchNumber} maxLength={80} disabled={busy} onChange={e=>setSearchNumber(e.target.value)} placeholder="Кадастровый номер"/></label><button className="primary-button" disabled={busy||!searchNumber.trim()} aria-label="Найти границы">Найти</button></form></div>
    <div className="land-picker-map"><FieldMap fields={mapRows} selected={selection===null?undefined:String(selection)} onSelect={id=>choose(Number(id))} onPoint={mapPoint} onZoom={setZoom} focus={focus} district={source==='public-map'?district:undefined} wide/><button className="land-locate icon-button" disabled={busy} aria-label="Моё местоположение" onClick={()=>void locate()}><Icon name="location"/></button><div className="land-map-hint" role="status">{busy?'Загружаем данные…':source==='demo'&&parcels.length?'Демо · вымышленные контуры':parcels.length?'Коснитесь контура для выбора':mode==='map'?(zoom<15?'Приблизьте карту к вашему участку':'Коснитесь земли, чтобы найти границы'):'Найдите участок по кадастровому номеру'}</div></div>
    <div className={`land-picker-bottom ${toolsOpen?'has-tools':''}`}>
      {error&&<div className="land-picker-alert" role="alert">{error}</div>}{message&&!toolsOpen&&<p className="land-picker-message" role="status">{message}</p>}
      {toolsOpen?<div className="land-picker-tools"><div className="section-head"><h3>Другие способы</h3><button className="icon-button" aria-label="Закрыть другие способы" onClick={()=>setToolsOpen(false)}><Icon name="close" size={18}/></button></div><label className="secondary-button file-action"><Icon name="layers" size={18}/>Загрузить GeoJSON<input type="file" accept=".geojson,.json,application/geo+json,application/json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void load(file);}}/></label><p>WGS84 · один контур без внутренних вырезов · до 2 МБ. Можно загрузить файл с несколькими участками и выбрать нужный.</p>{!existing&&<button className="secondary-button" disabled={busy} onClick={()=>{reset();setSource('demo');setParcels(DEMO_PARCELS);setToolsOpen(false);}}>Попробовать на демо-карте</button>}<a className="land-help-link" href={CADASTRE_URL} target="_blank" rel="noopener noreferrer">Официальная карта ЕГКН<Icon name="arrow" size={16}/></a>{!existing&&<button className="text-button" onClick={onPoint}>Пока отметить только точку</button>}</div>:<>
        {parcels.length>1&&<label className="land-result-select">{source==='demo'?'Демо-участки':'Найденные контуры'}<select aria-label="Выберите участок" value={selection===null?'':selection} onChange={e=>{if(e.target.value!=='')choose(Number(e.target.value));}}><option value="" disabled>Выберите контур · {parcels.length}</option>{parcels.map((p,i)=><option value={i} key={i}>{p.name} · {areaLabel(p.area)} га</option>)}</select></label>}
        {selected?<><div className="land-selection-summary"><div><span className="land-eyebrow">{effectiveSource==='demo'?'Демо · учебный контур':source==='public-map'?'Границы ЕГКН':'Контур из файла'}</span><strong>{number||name}</strong><small>{areaLabel(selected.area)} га{selected.region?` · ${selected.region}`:''}</small></div><button className="icon-button" aria-label={detailsOpen?'Скрыть данные участка':'Изменить название и посмотреть данные'} aria-expanded={detailsOpen} onClick={()=>setDetailsOpen(!detailsOpen)}><Icon name={detailsOpen?'up':'settings'} size={20}/></button></div>
          {detailsOpen&&<div className="land-selection-details workspace-form"><label>Название<input maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="Название участка"/></label>{effectiveSource!=='demo'&&<label>Кадастровый номер<input readOnly={effectiveSource==='public-map'} maxLength={80} value={number} onChange={e=>setNumber(e.target.value)} placeholder="Номер из документов"/></label>}<p>{selected.boundary.coordinates[0].length-1} вершин · площадь рассчитана по контуру.{selected.registeredAreaHa!==undefined?` В ЕГКН: ${areaLabel(selected.registeredAreaHa)} га.`:''}{selected.district?` ${selected.district}.`:''}</p></div>}
          {duplicate?<button className="secondary-button" disabled={busy} onClick={()=>void assertCurrent().then(()=>setMeta('selectedField',duplicate.id)).then(onClose).catch(e=>setError(humanError(e)))}>Уже добавлен · открыть участок</button>:<button className="primary-button" disabled={busy||!name.trim()} onClick={()=>void submit()}>{busy?'Подождите…':effectiveSource==='demo'?'Сохранить демо-участок':existing?'Сохранить границы':'Добавить этот участок'}</button>}<p className="land-picker-footnote">{effectiveSource==='demo'?'Учебные границы EGIN, не сведения кадастра.':'Проверьте контур. Добавление не подтверждает право собственности.'}</p>
        </>:!parcels.length&&<div className="land-picker-empty"><p>{mode==='map'?'Перемещайте карту двумя пальцами или перетаскиванием. Приблизьте нужное место и коснитесь участка.':'Введите номер из документов. Найденные границы появятся на карте — проверьте их перед добавлением.'}</p>{!signedIn&&<a className="text-button" href="#/auth" onClick={onClose}>Войти для поиска в ЕГКН<Icon name="right" size={16}/></a>}<button className="land-help-link" onClick={()=>setToolsOpen(true)}>Файл границ, демо и помощь<Icon name="right" size={15}/></button></div>}
      </>}
    </div>
  </dialog>;
}
function FieldEditor({workspaceOwner,existing,onClose}:{workspaceOwner:string;existing?:Row<Field>;onClose:()=>void}){
  const assertCurrent=useWorkspaceGuard(workspaceOwner);const [data,setData]=useState<Field>(existing?.data||{name:'',latitude:51.1694,longitude:71.4491,area:0,crop:'unknown'});const [coordinatesSet,setCoordinatesSet]=useState(!!existing),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[deleteConfirm,setDelete]=useState(false);const point=(latitude:number,longitude:number)=>{setData(d=>({...d,latitude,longitude}));setCoordinatesSet(true);};const f=previewRow(data);
  async function locate(){setError('');setBusy(true);try{if(!navigator.geolocation)throw new Error('Геолокация недоступна');const p=await new Promise<GeolocationPosition>((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:15000,maximumAge:0}));await assertCurrent();point(p.coords.latitude,p.coords.longitude);setNotice(`Точность около ${Math.round(p.coords.accuracy)} м. Это точка, а не границы участка.`);}catch{setError('Не удалось определить местоположение. Разрешите геолокацию или отметьте точку на карте.');}finally{setBusy(false);}}
  return <Sheet title={existing?'Настройки участка':'Точка участка'} onClose={onClose}><form className="workspace-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{if(!coordinatesSet)throw new Error('Выберите точку участка');await assertCurrent();const row=await saveForOwner({...data,name:data.name.trim()},existing,workspaceOwner);await assertCurrent();await setMeta('selectedField',row.id);onClose();}catch(err){setError(humanError(err));}finally{setBusy(false);}}}><label>Название<input required maxLength={80} value={data.name} onChange={e=>setData({...data,name:e.target.value})} placeholder="Например, Северное поле"/></label>{existing&&<label>Культура<select value={data.crop} onChange={e=>setData({...data,crop:e.target.value as Field['crop']})}>{Object.entries(cropNames).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label>}<label>{data.boundary?'Площадь по контуру, га':'Площадь, га'}<input type="number" min="0" max="1000000" step="any" required readOnly={!!data.boundary} value={data.area} onChange={e=>setData({...data,area:Number(e.target.value)})}/></label><FieldMap fields={coordinatesSet?[f]:[]} selected="preview" onPoint={data.boundary?undefined:point}/>{!data.boundary&&<><small className="form-help">Коснитесь карты, чтобы отметить точку. Границы можно добавить файлом позже.</small><button className="secondary-button" type="button" disabled={busy} onClick={()=>void locate()}><Icon name="location" size={18}/>Моё местоположение</button><details className="land-coordinate-details"><summary>Ввести координаты</summary><div className="form-columns"><label>Широта<input type="number" min="-90" max="90" step="any" required value={data.latitude} onChange={e=>point(Number(e.target.value),data.longitude)}/></label><label>Долгота<input type="number" min="-180" max="180" step="any" required value={data.longitude} onChange={e=>point(data.latitude,Number(e.target.value))}/></label></div></details></>}<Notice>{notice}</Notice><Notice error>{error}</Notice><button className="primary-button" disabled={busy||!coordinatesSet||!data.name.trim()}>Сохранить участок</button>{existing&&(deleteConfirm?<div className="delete-confirm"><p>Удалить участок? События, записи и датчики сохранятся.</p><button className="secondary-button" type="button" disabled={busy} onClick={async()=>{setBusy(true);try{await assertCurrent();await remove(existing);await assertCurrent();await setMeta('selectedField','');onClose();}catch(e){setError(humanError(e));}finally{setBusy(false);}}}>Подтвердить удаление</button></div>:<button className="text-button" type="button" onClick={()=>setDelete(true)}>Удалить участок</button>)}</form></Sheet>;
}
