import { useState } from 'react';
import { useRows,useMeta } from '../../entities/workspace/hooks';
import { addAsset,save,remove } from '../../entities/workspace/db';
import type { Entry,Field,Row } from '../../entities/workspace/types';
import { humanError } from '../../entities/workspace/api';
import { Sheet } from '../../shared/ui/Sheet';
import { Icon } from '../../shared/ui/Icon';
import { Page,Notice,Empty } from './ui';
import { BlobPreview,SavedAsset,VoiceRecorder,imageBlob } from './media';
const today=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
function Editor({existing,onClose}:{existing?:Row<Entry>;onClose:()=>void}){const {rows:fields}=useRows<Field>('field');const [title,setTitle]=useState(existing?.data.title||''),[text,setText]=useState(existing?.data.text||''),[date,setDate]=useState(existing?.data.date||today()),[fieldId,setField]=useState(existing?.data.fieldId||'');const [saved,setSaved]=useState(existing?.data.assets||[]),[blobs,setBlobs]=useState<Blob[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[recording,setRecording]=useState(false),[confirmDelete,setConfirmDelete]=useState(false);
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const assets=[...saved];for(const b of blobs)assets.push(await addAsset(b,b.type.startsWith('image/')?'Фото растения':'Голосовая заметка'));await save('entry',{title:title.trim(),text,date,fieldId,assets},existing);onClose();}catch(e){setError(humanError(e));}finally{setBusy(false);}}
return <Sheet title={existing?'Запись дневника':'Новая запись'} onClose={()=>{if(!busy&&!recording)onClose();}}><form className="workspace-form" onSubmit={submit}><label>Заголовок<input autoFocus required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Что происходит на участке?"/></label><div className="form-columns"><label>Дата<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>Участок<select aria-label="Участок" value={fieldId} onChange={e=>setField(e.target.value)}><option value="">Без участка</option>{fields.map(f=><option key={f.id} value={f.id}>{f.data.name}</option>)}</select></label></div><label>Наблюдения<textarea aria-label="Наблюдения" rows={5} maxLength={10000} value={text} onChange={e=>setText(e.target.value)} placeholder="Состояние растений, выполненные работы, важные детали…"/></label><div className="attachment-list">{saved.map(id=><div key={id}><SavedAsset id={id}/><button type="button" className="text-button" onClick={()=>setSaved(saved.filter(x=>x!==id))}>Убрать вложение</button></div>)}{blobs.map((b,i)=><div key={i}><BlobPreview blob={b}/><button type="button" className="text-button" onClick={()=>setBlobs(blobs.filter((_,n)=>n!==i))}>Убрать вложение</button></div>)}</div>{saved.length+blobs.length<8&&<div className="capture-actions"><label className="secondary-button file-action"><Icon name="camera" size={19}/>Фото растения<input aria-label="Добавить фото" type="file" accept="image/*" capture="environment" disabled={busy} onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(f){setBusy(true);try{const blob=await imageBlob(f);setBlobs(x=>[...x,blob]);}catch(err){setError(humanError(err));}finally{setBusy(false);}}}}/></label><VoiceRecorder onReady={b=>setBlobs(x=>[...x,b])} onError={setError} onRecording={setRecording}/></div>}<small className="form-help">До 8 вложений. Фото уменьшаются до 1600 px, голосовая заметка — до 2 минут. Запись сохраняется и без интернета.</small><Notice error>{error}</Notice><button className="primary-button" disabled={busy||recording||!title.trim()}>{busy?'Сохраняем…':'Сохранить запись'}</button>{existing&&(confirmDelete?<div className="delete-confirm"><p>Удалить запись и её содержимое из дневника на всех устройствах после синхронизации?</p><button type="button" className="secondary-button" onClick={async()=>{try{await remove(existing);onClose();}catch(e){setError(humanError(e));}}}>Да, удалить запись</button><button type="button" className="text-button" onClick={()=>setConfirmDelete(false)}>Отмена</button></div>:<button type="button" className="text-button" onClick={()=>setConfirmDelete(true)}>Удалить запись</button>)}</form></Sheet>;}
export default function JournalPage(){const {rows,error}=useRows<Entry>('entry'),{rows:fields}=useRows<Field>('field');const [editing,setEditing]=useState<Row<Entry>|'new'|null>(null),[query,setQuery]=useState(''),[field,setField]=useState('');const status=useMeta('syncStatus',{state:'guest',message:'Записи сохраняются на телефоне'});const filtered=rows.filter(r=>(!field||r.data.fieldId===field)&&`${r.data.title} ${r.data.text}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a,b)=>b.data.date.localeCompare(a.data.date));return <Page title="Дневник" back="/" action={<button className="icon-button" aria-label="Новая запись" onClick={()=>setEditing('new')}><Icon name="plus"/></button>}><div className="workspace-intro"><span className="eyebrow">Наблюдения и работы</span><p>Всё, что важно для вашего участка.</p></div><a className="sync-banner" href="#/settings/sync"><Icon name="rotate" size={18}/><span>{status.message}</span></a><div className="workspace-form"><label className="search-label">Поиск записей<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="По заголовку или тексту"/></label><label>Участок<select aria-label="Участок" value={field} onChange={e=>setField(e.target.value)}><option value="">Все участки</option>{fields.map(f=><option value={f.id} key={f.id}>{f.data.name}</option>)}</select></label></div><Notice error>{error}</Notice>{!filtered.length&&<Empty icon="journal" title={rows.length?'Ничего не найдено':'Первые наблюдения'}>Добавьте запись, фото или голосовую заметку. Они останутся на телефоне даже без связи.</Empty>}<div className="journal-list">{filtered.map(r=><button className="journal-card" key={r.id} onClick={()=>setEditing(r)}><div className="journal-meta"><time>{new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long'}).format(new Date(r.data.date+'T12:00:00'))}</time><span>{r.conflict?'Конфликт версий':r.dirty?'На телефоне':'В облаке'}</span></div><h2>{r.data.title}</h2><p>{r.data.text||'Без текстового описания'}</p><div className="journal-footer"><span>{fields.find(f=>f.id===r.data.fieldId)?.data.name||'Без участка'}</span>{r.data.assets.length>0&&<span><Icon name="camera" size={15}/>{r.data.assets.length}</span>}</div></button>)}</div><a className="secondary-button" href="#/settings/reports"><Icon name="share" size={18}/>Экспортировать дневник</a>{editing&&<Editor existing={editing==='new'?undefined:editing} onClose={()=>setEditing(null)}/>}</Page>;}
