import { useEffect,useRef,useState } from 'react';
import { localAsset } from '../../entities/workspace/db';
import { Icon } from '../../shared/ui/Icon';
import { humanError } from '../../entities/workspace/api';
export async function imageBlob(file:File):Promise<Blob>{if(file.size>25*1024*1024)throw new Error('Фото должно быть меньше 25 МБ');const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();const ratio=Math.min(1,1600/Math.max(image.naturalWidth,image.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.round(image.naturalWidth*ratio);canvas.height=Math.round(image.naturalHeight*ratio);canvas.getContext('2d')!.drawImage(image,0,0,canvas.width,canvas.height);return await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Не удалось обработать фото')),'image/jpeg',.85));}finally{URL.revokeObjectURL(url);}}
export function BlobPreview({blob,name='Вложение'}:{blob:Blob;name?:string}){const [url,setURL]=useState('');useEffect(()=>{const u=URL.createObjectURL(blob);setURL(u);return()=>URL.revokeObjectURL(u);},[blob]);return blob.type.startsWith('image/')?<img src={url} alt={name} className="entry-photo" loading="lazy"/>:<audio controls preload="metadata" src={url} aria-label={name}/>;}
export function SavedAsset({id}:{id:string}){const [blob,setBlob]=useState<Blob>();useEffect(()=>{let active=true;void localAsset(id).then(a=>{if(active)setBlob(a?.blob);});return()=>{active=false;};},[id]);return blob?<BlobPreview blob={blob}/>:<p className="attachment-pending">Вложение загрузится при синхронизации</p>;}
export function VoiceRecorder({onReady,onError,onRecording}:{onReady:(b:Blob)=>void;onError:(s:string)=>void;onRecording:(v:boolean)=>void}){const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),mounted=useRef(true);const [recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),[asking,setAsking]=useState(false);
useEffect(()=>{mounted.current=true;const stop=()=>{if(document.hidden&&recorder.current?.state==='recording')recorder.current.stop();};document.addEventListener('visibilitychange',stop);return()=>{mounted.current=false;recorder.current?.state==='recording'&&recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());document.removeEventListener('visibilitychange',stop);};},[]);
useEffect(()=>{if(!recording)return;const t=setInterval(()=>setSeconds(n=>{if(n>=119){recorder.current?.stop();return 120;}return n+1;}),1000);return()=>clearInterval(t);},[recording]);
async function start(){try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('Запись звука недоступна в этом браузере');setAsking(true);const s=await navigator.mediaDevices.getUserMedia({audio:true});if(!mounted.current){s.getTracks().forEach(t=>t.stop());return;}stream.current=s;const mime=['audio/webm','audio/mp4','audio/ogg'].find(m=>MediaRecorder.isTypeSupported(m));const r=new MediaRecorder(s,mime?{mimeType:mime}:{}),chunks:BlobPart[]=[];recorder.current=r;r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};r.onstop=()=>{s.getTracks().forEach(t=>t.stop());if(mounted.current){setRecording(false);onRecording(false);const b=new Blob(chunks,{type:r.mimeType.split(';')[0]});if(b.size)onReady(b);}};r.onerror=()=>{onError('Не удалось записать звук');r.state==='recording'&&r.stop();s.getTracks().forEach(t=>t.stop());};r.start();setSeconds(0);setRecording(true);onRecording(true);}catch(e){onError((e as Error).name==='NotAllowedError'?'Доступ к микрофону запрещён. Разрешите его в настройках браузера или устройства.':humanError(e));}finally{setAsking(false);}}
return <button type="button" className={`secondary-button ${recording?'is-recording':''}`} disabled={asking} onClick={()=>recording?recorder.current?.stop():void start()}><Icon name={recording?'pause':'mic'} size={19}/>{recording?`Остановить · ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`:asking?'Доступ к микрофону…':'Голосовая заметка'}</button>;}
