import { Capacitor } from '@capacitor/core';
import { download, nativeShare } from '../../shared/lib/files';
import { useState } from 'react';
import { useRows } from '../../entities/workspace/hooks';
import { localAsset } from '../../entities/workspace/db';
import type { Entry,Field } from '../../entities/workspace/types';
import { humanError } from '../../entities/workspace/api';
import { Page,Notice } from './ui';
import { Icon } from '../../shared/ui/Icon';
export const escapeHTML=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const csvCell=(s:string)=>'"'+(/^[=+@\-\t\r]/.test(s)?"'"+s:s).replaceAll('"','""')+'"';

const dataURL=(blob:Blob)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(r.error);r.readAsDataURL(blob);});
export default function ReportsPage(){const {rows}=useRows<Entry>('entry'),{rows:fields}=useRows<Field>('field');const [field,setField]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[format,setFormat]=useState('html'),[media,setMedia]=useState(true),[file,setFile]=useState<File>(),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');const selected=rows.filter(r=>(!field||r.data.fieldId===field)&&(!from||r.data.date>=from)&&(!to||r.data.date<=to)).sort((a,b)=>a.data.date.localeCompare(b.data.date));function invalidate(){setFile(undefined);setMessage('');}
async function build(){setError('');setBusy(true);try{if(from&&to&&from>to)throw new Error('Дата начала должна быть раньше окончания');if(!selected.length)throw new Error('В выбранном периоде нет записей');let content='',mime='';const assets:Record<string,string>={};let totalBytes=0;if(media&&format!=='csv')for(const r of selected)for(const id of r.data.assets){const a=await localAsset(id);if(!a)throw new Error('Некоторые вложения ещё не загружены. Синхронизируйте или выключите вложения.');if(!assets[id]){totalBytes+=a.blob.size;if(totalBytes>20*1024*1024)throw new Error('Вложения отчёта превышают 20 МБ. Сузьте период или отключите вложения.');assets[id]=await dataURL(a.blob);}}
if(format==='csv'){content='\uFEFF'+[['Дата','Участок','Заголовок','Наблюдения','Вложений'],...selected.map(r=>[r.data.date,fields.find(f=>f.id===r.data.fieldId)?.data.name||'',r.data.title,r.data.text,String(r.data.assets.length)])].map(line=>line.map(csvCell).join(';')).join('\r\n');mime='text/csv;charset=utf-8';}
else if(format==='json'){content=JSON.stringify({format:'egin-journal',version:1,exportedAt:new Date().toISOString(),fields:fields.filter(f=>selected.some(r=>r.data.fieldId===f.id)).map(f=>({id:f.id,...f.data})),entries:selected.map(r=>({id:r.id,...r.data})),attachments:assets},null,2);mime='application/json';}
else{content=`<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>История EGIN</title><style>body{font:16px/1.6 system-ui;color:#214d36;max-width:800px;margin:32px auto;padding:0 20px}h1{font-size:30px}article{border-top:1px solid #ccc;padding:24px 0;break-inside:avoid}img{max-width:100%;max-height:500px}audio{max-width:100%}p{white-space:pre-wrap}small{color:#52695c}@media print{audio{display:none}}</style><h1>egin. / История участка</h1><small>Сформирован ${escapeHTML(new Date().toLocaleString('ru-RU'))} · Записей: ${selected.length}</small>${selected.map(r=>`<article><small>${escapeHTML(r.data.date)} · ${escapeHTML(fields.find(f=>f.id===r.data.fieldId)?.data.name||'Без участка')}</small><h2>${escapeHTML(r.data.title)}</h2><p>${escapeHTML(r.data.text)}</p>${media?r.data.assets.map(id=>assets[id]?.startsWith('data:image/')?`<img src="${assets[id]}" alt="Фото растения">`:assets[id]?`<audio controls src="${assets[id]}"></audio>`:'').join(''):''}</article>`).join('')}</html>`;mime='text/html;charset=utf-8';}
const report=new File([content],`EGIN-история-${new Date().toISOString().slice(0,10)}.${format}`,{type:mime});setFile(report);setMessage(`Отчёт готов · ${Math.round(report.size/1024)||1} КБ`);}catch(e){setError(humanError(e));}finally{setBusy(false);}}
return <Page title="Отчёты и экспорт"><p className="page-description">Отчёт содержит сохранённые и импортированные записи истории. Погодные события и состояние подключений в этот экспорт не входят. Фото и аудио можно включить в HTML или JSON. Для PDF откройте HTML и выберите печать.</p><div className="workspace-form"><label>Участок<select aria-label="Участок" value={field} onChange={e=>{setField(e.target.value);invalidate();}}><option value="">Все участки</option>{fields.map(f=><option key={f.id} value={f.id}>{f.data.name}</option>)}</select></label><div className="form-columns"><label>С даты<input type="date" value={from} onChange={e=>{setFrom(e.target.value);invalidate();}}/></label><label>По дату<input type="date" value={to} onChange={e=>{setTo(e.target.value);invalidate();}}/></label></div><label>Формат<select aria-label="Формат" value={format} onChange={e=>{setFormat(e.target.value);invalidate();}}><option value="html">HTML — отчёт с фото и аудио</option><option value="csv">CSV — таблица для Excel</option><option value="json">JSON — данные и вложения</option></select></label>{format!=='csv'&&<label className="checkbox-row"><input type="checkbox" checked={media} onChange={e=>{setMedia(e.target.checked);invalidate();}}/>Включить фото и аудио</label>}<p className="form-help">Выбрано записей: {selected.length}</p><button className="primary-button" disabled={busy||!selected.length} onClick={()=>void build()}>{busy?'Формируем отчёт…':'Сформировать отчёт'}</button><Notice error>{error}</Notice><Notice>{message}</Notice>{file&&<div className="report-actions"><button className="secondary-button" onClick={()=>void download(file,file.name).catch(e=>setError(humanError(e)))}><Icon name="down" size={18}/>{Capacitor.isNativePlatform()?'Сохранить файл':'Скачать файл'}</button><button className="secondary-button" onClick={async()=>{setError('');try{if(Capacitor.isNativePlatform()){await nativeShare(file,file.name);setMessage('Открыто меню отправки');}else if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'История EGIN'});setMessage('Отчёт передан в меню «Поделиться»');}else{await download(file,file.name);setMessage('Отправка файлов недоступна в этом браузере. Файл скачан — отправьте его из папки загрузок.');}}catch(e){if((e as Error).name!=='AbortError')setError(humanError(e));}}}><Icon name="share" size={18}/>Поделиться</button></div>}</div></Page>;}
