import { readFile, writeFile, rename } from 'node:fs/promises';
const label = process.env.PROFILE_LABEL || 'before';
const report = JSON.parse(await readFile(`artifacts/performance-${label}.json`, 'utf8'));
const round = value => value == null ? '—' : Math.round(value);
const kib = value => (value / 1024).toFixed(1);
const rows = [...report.results].sort((a, b) => ['normal', 'fast4g-cpu4', 'slow4g-cpu4'].indexOf(a.profile) - ['normal', 'fast4g-cpu4', 'slow4g-cpu4'].indexOf(b.profile) || ['/', '/map', '/assistant', '/community', '/market'].indexOf(a.route) - ['/', '/map', '/assistant', '/community', '/market'].indexOf(b.route));
const table = rows.map(r => `| ${r.profile} | ${r.route} | ${round(r.ttfbMs)} | ${round(r.fcpMs)} | ${round(r.lcp?.timeMs)} | ${round(r.readyMs)} | ${kib(r.jsTransferBytes)} | ${r.apiRequests}/${kib(r.apiTransferBytes)} | ${round(r.longTaskTotalMs)} | ${round(r.observedMenuClickToPaintMs)} | ${round(r.mapWebglFirstDrawMs)} |`).join('\n');
const exceptions = rows.flatMap(r => [...(r.apiFailures || r.requests.filter(q => q.path.startsWith('/api/') && q.status >= 400)).map(e => `${r.profile} ${r.route}: ${e.path} HTTP ${e.status}`), ...(r.errors || []), ...(r.readinessError ? [r.readinessError] : [])]);
const output = `# EGIN browser performance: ${label}\n\nMeasured ${report.measuredAt}, ${report.environment.browser}, localhost production build. JSON contains individual network requests and long tasks.\n\nThis is one laboratory sample per route/profile at 390×844, with a cold browser cache and retained server/provider caches. It is not Lighthouse, field Core Web Vitals, or measurement on a physical smartphone. CPU throttling is relative to the current machine. Maps use headless Chrome software WebGL (SwiftShader). External tile/provider timing varies. LCP is observed until a bounded post-ready interval, not an unconstrained page lifetime.\n\nNetwork profiles are explicitly configured in the harness: normal unthrottled / CPU 1×; Fast4G 1.6 Mbit/s down, 750 Kbit/s up, 150 ms latency / CPU 4×; Slow4G 500 Kbit/s down/up, 400 ms latency / CPU 4×. These are named test scenarios, not a claim to reproduce all real 4G networks.\n\n| Profile | Route | TTFB ms | FCP ms | LCP ms | UI ready ms | JS transfer KiB | API count/KiB | Long-task total ms | Menu click→paint ms | First WebGL draw ms |\n|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n${table}\n\nThe menu measurement records a real trusted browser click to completion of two animation frames. It is an observed local interaction sample, **not INP**. Full field INP requires real user monitoring. First WebGL draw measures renderer initialization and does not guarantee all remote map tiles have arrived. Transfer sizes include response headers; requests still open at collection time have a null byte count.\n\nChecks: ${exceptions.length ? exceptions.map(e => `\n- ${e}`).join('') : 'No page JavaScript exceptions or HTTP API failures were observed.'}\n\n## Reproduce\n\nRun the existing production containers, then:\n\n\`\`\`sh\nnode scripts/profile-browser.mjs\nnode scripts/profile-report.mjs\n\`\`\`\n\nUses the already installed Playwright and Chrome; installs nothing. Login is restricted to localhost by default. The script logs in with the demo account, loads authenticated pages, and opens a navigation menu. It does not send messages, mutate product records, invoke LLM generation, or alter deployment state.\n\nAfter changes use \`PROFILE_LABEL=after node scripts/profile-browser.mjs\` and the same label for the report command. If the home no longer initializes WebGL, set \`PROFILE_MAP_ROUTES=/map\`. To rerun selected cases without replacing others use \`PROFILE_RESUME=1 PROFILE_MODES=fast4g-cpu4,slow4g-cpu4 PROFILE_ROUTES=/ node scripts/profile-browser.mjs\`.\n`;
let finalOutput = rows.every(row => row.cache.startsWith('warm'))
  ? output.replace('with a cold browser cache and retained server/provider caches', 'with warm browser/Service Worker/IndexedDB caches after an unthrottled warmup, and retained server/provider caches')
  : output;
if (report.recovered_summary) finalOutput = finalOutput.replace('JSON contains individual network requests and long tasks.', '**Recovered baseline summary:** an ENOSPC disk-full error truncated the detailed JSON. The 15 table rows were preserved independently and restored to JSON with their displayed precision; individual request/long-task traces are unavailable. These are the original measurements, not a rerun against changed code.');
if (report.environment.workingTreeDirty !== undefined) finalOutput += `\nSource provenance: base commit \`${report.environment.revision}\`; working tree dirty: **${report.environment.workingTreeDirty}**. A dirty measurement describes the tested working tree, not an unchanged checkout of that commit.\n`;
finalOutput += '\nNetwork shaping caveat: the profile names describe configured CDP bandwidth/latency/CPU settings. Recorded NavigationTiming TTFB on loopback stayed well below the configured 150/400 ms latency in both runs; it does not demonstrate an effective 150/400 ms RTT. These are controlled configured-CDP scenarios, not validated real-world 4G RTT measurements.\n';
if (rows.some(row => row.serviceWorkerMode)) finalOutput += rows.every(row => row.serviceWorkerMode === 'block')
  ? '\nCold measurement isolates the network navigation path with Service Workers blocked in the profiling browser; the baseline had no Service Worker. This ensures page CDP throttling and transfer-byte accounting include dynamic chunks. Production Service Worker functionality is tested separately; these cold values do not include Service Worker installation or interception overhead.\n'
  : '\nWarm measurement retains the actual Service Worker. Its Resource Timing entries are recorded separately and their JS transfer sizes supplement page CDP counters; warmup entries are cleared before navigation. Page CDP throttling is not guaranteed to cover a Service Worker cache miss, so warm figures characterize cached visits, not an uncached network path.\n';
if (rows.some(row => row.scriptDurationMs != null || row.observedMenuEventTimingMs != null)) {
  finalOutput += '\n## Supplementary laboratory timings\n\nField INP: **unavailable**. The Event Timing values below are the maximum observed duration from a single synthetic, trusted menu interaction; they are not a field INP result. Event Timing durations are rounded by the browser and entries below its reporting threshold can be absent. Script CPU and main-thread task time are CDP counter deltas over the measured navigation and bounded observation window, excluding warmup counters.\n\n| Profile | Route | Script CPU ms | Main-thread task ms | Menu Event Timing ms |\n|---|---|---:|---:|---:|\n';
  finalOutput += rows.map(row => `| ${row.profile} | ${row.route} | ${round(row.scriptDurationMs)} | ${round(row.mainThreadTaskMs)} | ${round(row.observedMenuEventTimingMs)} |`).join('\n') + '\n';
}
const target = `artifacts/performance-${label}.md`;
await writeFile(target + '.tmp', finalOutput + '\nFor an independent warm-home measurement: `PROFILE_LABEL=after-warm-home PROFILE_CACHE=warm PROFILE_ROUTES=/ PROFILE_MAP_ROUTES=/map node scripts/profile-browser.mjs`. Warm results are not a cold-to-cold comparison.\n');
await rename(target + '.tmp', target);
console.log(`Wrote artifacts/performance-${label}.md (${rows.length} samples)`);
