import { lazy,Suspense,useEffect,useState } from 'react';
import { Capacitor } from '@capacitor/core';
import { useMeta,useRows } from '../../entities/workspace/hooks';
import { discardLocal } from '../../entities/workspace/db';
import type { Profile,SessionUser } from '../../entities/workspace/types';
import type { Preferences } from '../../shared/lib/preferences';
import { humanError } from '../../entities/workspace/api';
import { Page,LinkRow,Notice,Toggle } from '../workspace/ui';
const ProfilePage=lazy(()=>import('./ProfilePage'));
const SecurityPage=lazy(()=>import('./ProfilePage').then(m=>({default:m.SecurityPage})));
const SyncPage=lazy(()=>import('./SyncPage'));
const NotificationsPage=lazy(()=>import('./NotificationsPage'));
const SensorsPage=lazy(()=>import('../workspace/SensorsPage'));
const ReportsPage=lazy(()=>import('../workspace/ReportsPage'));
export default function SettingsPage({path,onInstall,preferences,onChange}:{path:string;onInstall:()=>void;preferences:Preferences;onChange:(p:Preferences)=>void}){const user=useMeta<SessionUser|null>('user',null),{rows}=useRows<Profile>('profile');const section=path.split('/')[2]||'';return <Suspense fallback={<div className="page-loading">Открываем настройки…</div>}>{section==='profile'?<ProfilePage/>:section==='security'?<SecurityPage/>:section==='sync'?<SyncPage/>:section==='sensors'?<SensorsPage/>:section==='reports'?<ReportsPage/>:section==='notifications'?<NotificationsPage/>:section==='api'?<APIPage/>:section==='app'?<AppSettings onInstall={onInstall} preferences={preferences} onChange={onChange}/>:<Page title="Настройки" back="/"><a className="profile-summary" href="#/settings/profile"><span className="profile-avatar">{(rows[0]?.data.name||user?.name||'E').slice(0,1).toUpperCase()}</span><span><strong>{rows[0]?.data.name||user?.name||'Мой профиль'}</strong><small>{user?'Профиль EGIN':'Локальный режим · войти в профиль'}</small></span></a><section className="settings-group"><h2>Хозяйство</h2><LinkRow href="/fields" title="Мои участки" description="Карта, координаты и культуры" icon="map"/><LinkRow href="/settings/sensors" title="Датчики" description="QR, привязка к участкам, реестр" icon="layers"/><LinkRow href="/settings/api" title="API и интеграции" description="Погода, датчики и аналитика" icon="cloud" badge="В разработке"/></section><section className="settings-group"><h2>Записи и данные</h2><LinkRow href="/journal" title="Дневник" description="Наблюдения, фотографии и голос" icon="journal"/><LinkRow href="/settings/sync" title="Синхронизация" description="Очередь отправки и конфликты версий" icon="rotate"/><LinkRow href="/settings/reports" title="Отчёты и экспорт" description="Период, участок и отправка файлов" icon="share"/></section><section className="settings-group"><h2>Личное</h2><LinkRow href="/settings/profile" title="Мой профиль" description="Имя, хозяйство и контакт" icon="user"/><LinkRow href="/settings/security" title="Безопасность и вход" description="Passkey и восстановление доступа" icon="lock"/><LinkRow href="/settings/notifications" title="Уведомления" description="Разрешения и проверка доставки" icon="bell"/></section><section className="settings-group"><h2>Приложение</h2><LinkRow href="/settings/app" title="Хранение и отображение" description="Офлайн-данные, анимация, установка" icon="phone"/></section><p className="settings-version">EGIN · мобильная версия 0.3</p></Page>}</Suspense>;}
function APIPage(){return <Page title="API и интеграции"><div className="workspace-card"><span className="status-label">В разработке</span><h2>Единое подключение данных</h2><p>Здесь появятся ключи доступа, проверка соединения и журнал обмена. Секретные ключи будут храниться на сервере.</p></div><div className="integration-list"><article className="workspace-card"><h2>Open-Meteo</h2><span className="status-label">Подключён</span><p>Текущая погода и прогноз по координатам выбранного участка. API-ключ не требуется.</p><a className="text-button" href="#/weather">Открыть погоду</a></article>{[['Google Weather','Следующий источник погодных данных'],['Умные датчики','Автоматический приём показаний и контроль связи'],['Аналитика культуры','Определение фазы роста по данным участка']].map(([title,description])=><article className="workspace-card" key={title}><h2>{title}</h2><span className="status-label">В разработке</span><p>{description}. Подключение пока недоступно.</p></article>)}</div><Notice>Добавленные датчики пока хранятся в реестре. Их показания и состояние растений не генерируются.</Notice></Page>;}
function AppSettings({onInstall,preferences,onChange}:{onInstall:()=>void;preferences:Preferences;onChange:(p:Preferences)=>void}){const [estimate,setEstimate]=useState<StorageEstimate>(),[persistent,setPersistent]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[confirm,setConfirm]=useState(false);const load=()=>{void navigator.storage?.estimate().then(setEstimate);void navigator.storage?.persisted().then(setPersistent);};useEffect(load,[]);return <Page title="Приложение"><section className="workspace-card"><h2>Отображение</h2><Toggle title="Анимация 3D" description="Движение растений и осадков. Системное уменьшение движения имеет приоритет." on={preferences.motion} onChange={()=>onChange({...preferences,motion:!preferences.motion})}/><dl className="settings-facts"><div><dt>Оформление</dt><dd>Белый и тёмно-зелёный</dd></div><div><dt>Язык</dt><dd>Русский</dd></div><div><dt>Единицы</dt><dd>°C · км/ч · мм · га</dd></div></dl></section><section className="workspace-card"><h2>Хранилище телефона</h2><p>Записи, фото, аудио и кеш приложения. Очистка данных браузера удалит локальные копии.</p><dl className="settings-facts"><div><dt>Занято</dt><dd>{estimate?.usage!==undefined?(estimate.usage/1048576).toFixed(1)+' МБ':'Неизвестно'}</dd></div><div><dt>Защита от автоочистки</dt><dd>{persistent?'Разрешена':'Не предоставлена'}</dd></div></dl>{navigator.storage?.persist&&<button className="secondary-button" onClick={async()=>{const ok=await navigator.storage.persist();setPersistent(ok);setMessage(ok?'Браузер разрешил постоянное хранение':'Браузер пока не предоставил постоянное хранение. Экспортируйте важные записи.');}}>Запросить постоянное хранение</button>}<a href="#/settings/reports" className="text-button">Экспортировать записи</a>{confirm?<><p>Удалить синхронизированные копии записей и вложений с этого телефона? Несинхронизированные записи защищены. Для повторной загрузки понадобится сеть.</p><button className="secondary-button" onClick={async()=>{try{await discardLocal();setMessage('Локальные копии удалены. Их можно загрузить синхронизацией.');setConfirm(false);load();}catch(e){setError(humanError(e));}}}>Очистить локальные копии</button><button className="text-button" onClick={()=>setConfirm(false)}>Отмена</button></>:<button className="text-button" onClick={()=>setConfirm(true)}>Очистить синхронизированные копии</button>}</section>{!Capacitor.isNativePlatform()&&<button className="primary-button" onClick={onInstall}>Добавить на главный экран</button>}<Notice error>{error}</Notice><Notice>{message}</Notice><p className="settings-version">Карта © OpenStreetMap · Погода Open-Meteo</p></Page>;}
