const { chromium, webkit } = require('@playwright/test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const fixture = require('./fixtures/open-meteo.json');
const out = process.env.EGIN_SCREENSHOTS || '/workspace/test-results/mobile';
const origin = process.env.EGIN_URL || 'http://127.0.0.1:4934';
(async () => {
  fs.mkdirSync(out, { recursive: true });
  const browser = await chromium.launch({ args: ['--no-sandbox', '--enable-unsafe-swiftshader'] });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true, reducedMotion: 'reduce' });
  let offline = false;
  await context.route('https://api.open-meteo.com/**', route => offline ? route.abort() : route.fulfill({ json: fixture }));
  await context.route('**/api/news', route => route.fulfill({ json: require('./fixtures/news.json') }));
  await context.route('https://eldala.kz/uploads/**', route => route.fulfill({ status: 404 }));
  const page = await context.newPage();
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(origin);
  await page.locator('.crop-canvas[data-ready="true"]').waitFor();
  await page.waitForTimeout(200);
  assert.equal(await page.locator('.weather-report, .field-select, .tasks-section, .greeting-row').count(), 0);
  assert.equal(await page.locator('.growth-track button').count(), 0);
  await page.locator('.news-item').first().waitFor();
  assert.equal(await page.locator('.news-item').count(), 3);
  assert.equal(await page.locator('.nav-item.active .nav-icon').evaluate(el => getComputedStyle(el).backgroundColor), 'rgba(0, 0, 0, 0)');
  assert.equal(await page.locator('.nav-item.active').evaluate(el => getComputedStyle(el).color === getComputedStyle(el.querySelector('.nav-icon')).color), true);
  assert.equal(await page.evaluate(() => getComputedStyle(document.querySelector('.mobile-shell')).backgroundColor), 'rgb(255, 255, 255)');
  assert.ok((await page.locator('.plant-hero').boundingBox()).y < 100, '3D comes first');
  await page.screenshot({ path: `${out}/home-390.png` });
  for (const width of [320, 360, 390, 430, 480, 768, 1440]) {
    await page.setViewportSize({ width, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `overflow at ${width}`);
    assert.equal(await page.locator('.nav-item').count(), 5);
    const nav = await page.locator('.mobile-nav').boundingBox();
    assert.ok(nav.width <= 480 && Math.abs(nav.y + nav.height - 844) < 1);
    assert.ok((await page.locator('.mobile-shell').boundingBox()).width <= 480);
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => { document.documentElement.style.setProperty('--safe-area-inset-top', '47px'); document.documentElement.style.setProperty('--safe-area-inset-bottom', '34px'); });
  assert.equal(await page.locator('.mobile-shell').evaluate(el => getComputedStyle(el).paddingTop), '47px');
  assert.equal(await page.locator('.mobile-nav').evaluate(el => getComputedStyle(el).paddingBottom), '39px');
  await page.evaluate(() => { document.documentElement.style.removeProperty('--safe-area-inset-top'); document.documentElement.style.removeProperty('--safe-area-inset-bottom'); });
  await page.getByRole('button', { name: 'Приблизить модель', exact: true }).click();
  assert.equal(await page.locator('.crop-canvas').getAttribute('data-zoom'), '1.1');
  await page.getByRole('button', { name: 'Отдалить модель', exact: true }).click();
  await page.getByRole('button', { name: 'Сбросить ракурс', exact: true }).click();
  assert.equal(await page.locator('.crop-canvas').getAttribute('data-zoom'), '1.0');
  await page.getByRole('button', { name: 'Слои модели', exact: true }).click();
  await page.getByRole('button', { name: /Корневая система/ }).click();
  await page.getByRole('button', { name: /Показатели участка/ }).click();
  await page.getByRole('button', { name: 'Применить', exact: true }).click();
  await page.locator('.crop-canvas[data-roots="true"]').waitFor();
  await page.getByText('Почва: нет данных', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Развернуть 3D', exact: true }).click();
  await page.locator('.sheet-large .crop-canvas[data-ready="true"]').waitFor();
  assert.equal(await page.locator('canvas').count(), 1, 'only one WebGL canvas in full screen');
  await page.getByRole('button', { name: 'Корни', exact: true }).click();
  await page.getByRole('button', { name: 'Данные', exact: true }).click();
  await page.getByRole('button', { name: 'Приблизить модель', exact: true }).click();
  await page.screenshot({ path: `${out}/fullscreen.png` });
  await page.getByRole('button', { name: 'Закрыть', exact: true }).click();
  await page.locator('.crop-canvas[data-ready="true"]').waitFor();
  assert.equal(await page.getByRole('button', { name: 'Развернуть 3D', exact: true }).evaluate(el => el === document.activeElement), true);
  for (const [label, condition, period] of [['Утро', 'sun', 'dawn'], ['День', 'sun', 'day'], ['Вечер', 'sun', 'dusk'], ['Ночь', 'night', 'night'], ['Дождь', 'rain'], ['Снег', 'snow'], ['Облачно', 'cloud'], ['Ветер', 'wind']]) {
    await page.getByRole('button', { name: 'Условия 3D-просмотра', exact: true }).click();
    await page.getByRole('dialog').getByRole('button', { name: label, exact: true }).click();
    await page.getByRole('button', { name: 'Вернуться к модели', exact: true }).click();
    await page.locator(`.crop-canvas[data-condition="${condition}"]`).waitFor();
    if (period) assert.equal(await page.locator('.crop-canvas').getAttribute('data-period'), period);
    await page.waitForTimeout(120);
    await page.locator('.plant-hero').screenshot({ path: `${out}/scene-${label}.png` });
  }
  await page.getByRole('button', { name: 'Условия 3D-просмотра', exact: true }).click();
  await page.getByRole('button', { name: /По погоде участка/ }).click();
  await page.keyboard.press('Escape');
  await page.locator('.news-filters').getByRole('button', { name: 'Технологии', exact: true }).click();
  assert.equal(await page.locator('.news-item').count(), 1);
  assert.match(await page.locator('.news-item').getAttribute('href'), /^https:\/\/eldala.kz\//);
  await page.locator('.news-filters').getByRole('button', { name: 'Все', exact: true }).click();
  await page.locator('.growth-caption').click();
  await page.getByRole('heading', { name: 'Автоматическое развитие', exact: true }).waitFor();
  await page.getByText('Ещё не подключены', { exact: true }).waitFor();
  await page.keyboard.press('Escape');
  await page.getByRole('link', { name: 'Погода', exact: true }).click();
  await page.locator('.weather-report').waitFor();
  assert.equal(await page.locator('canvas').count(), 0, 'home renderer disposed on navigation');
  await page.screenshot({ path: `${out}/weather-390.png` });
  for (const width of [320, 360, 390, 430]) {
    await page.setViewportSize({ width, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `weather overflow at ${width}`);
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('tab', { name: 'На 10 дней', exact: true }).click();
  assert.equal(await page.locator('.forecast-day').count(), 10);
  await page.locator('.forecast-day').first().click();
  await page.getByText('Осадки за сутки', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Закрыть', exact: true }).click();
  await page.getByRole('tab', { name: 'По часам', exact: true }).click();
  await page.getByRole('button', { name: 'Осадки', exact: true }).click();
  assert.equal(await page.locator('.forecast-plot rect').count(), 24);
  await page.locator('.forecast-hour').nth(1).click();
  await page.getByText('Влажный термометр', { exact: true }).waitFor();
  assert.equal(await page.locator('.sheet .weather-metric').count(), 15);
  assert.equal(await page.locator('.sheet .metric-heatIndex .weather-metric-value').textContent(), '—');
  await page.locator('.sheet').screenshot({ path: `${out}/hour-details.png` });
  await page.getByRole('button', { name: 'Закрыть', exact: true }).click();
  await page.getByRole('button', { name: 'Ветер, подробнее', exact: true }).click();
  await page.getByRole('heading', { name: 'Ветер', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Закрыть', exact: true }).click();
  await page.getByRole('button', { name: 'Все погодные показатели', exact: true }).click();
  await page.getByRole('button', { name: 'Тепловой индекс, подробнее', exact: true }).waitFor();
  await page.locator('.weather-report').screenshot({ path: `${out}/weather-report.png` });
  await page.getByRole('button', { name: 'Свернуть показатели', exact: true }).click();
  for (const label of ['Чат', 'Рынок']) {
    await page.getByRole('link', { name: label, exact: true }).click();
    await page.getByText('В разработке', { exact: true }).waitFor();
  }
  await page.goto(origin + '/#/settings/app');
  await page.getByRole('button', { name: 'Добавить на главный экран', exact: true }).click();
  await page.getByRole('heading', { name: 'EGIN на вашем телефоне' }).waitFor();
  await page.keyboard.press('Escape');
  await page.getByRole('link', { name: 'Главная', exact: true }).click();
  await page.evaluate(() => { localStorage.setItem('egin.mobile.v1', JSON.stringify({ crop: 'wheat', stages: { wheat: 0 } })); });
  await page.reload();
  await page.locator('.crop-canvas[data-stage="2"][data-ready="true"]').waitFor();
  await page.evaluate(() => Promise.race([navigator.serviceWorker.ready.then(()=>true), new Promise((_,reject)=>setTimeout(()=>reject(new Error('Service worker activation timed out')),20000))]));
  await page.reload();
  await page.waitForFunction(() => !!navigator.serviceWorker.controller);
  offline = true;
  await context.setOffline(true);
  await page.reload();
  await page.locator('.crop-canvas[data-ready="true"]').waitFor();
  await page.getByRole('link', { name: 'Погода', exact: true }).click();
  await page.getByText(/Нет связи. Показан сохранённый прогноз/).waitFor();
  assert.deepEqual(errors, []);
  const recovery = await browser.newContext({ viewport: { width: 320, height: 640 }, reducedMotion: 'reduce', serviceWorkers: 'block' });
  let fail = true;
  const rainAtNight = structuredClone(fixture);
  rainAtNight.current.weather_code = 63;
  rainAtNight.current.is_day = 0;
  await recovery.route('https://api.open-meteo.com/**', route => fail ? route.fulfill({ status: 429, body: 'Rate limited' }) : route.fulfill({ json: rainAtNight }));
  const retryPage = await recovery.newPage();
  await retryPage.goto(origin + '/#/weather');
  await retryPage.getByText('Не удалось загрузить погоду. Проверьте соединение.', { exact: true }).waitFor();
  assert.equal(await retryPage.locator('.weather-report').count(), 0);
  fail = false;
  await retryPage.getByRole('button', { name: 'Повторить', exact: true }).click();
  await retryPage.locator('.weather-report').waitFor();
  await retryPage.getByRole('link', { name: 'Главная', exact: true }).click();
  await retryPage.locator('.crop-canvas[data-condition="rain"][data-night="true"][data-ready="true"]').waitFor();
  await retryPage.screenshot({ path: `${out}/night-rain-320.png` });
  assert.equal(await retryPage.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await recovery.close();
  await browser.close();
  const safari = await webkit.launch();
  const ios = await safari.newContext({ viewport: { width: 375, height: 812 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce' });
  await ios.route('https://api.open-meteo.com/**', route => route.fulfill({ json: fixture }));
  const tab = await ios.newPage();
  await tab.goto(origin);
  await tab.locator('.crop-canvas[data-ready="true"]').waitFor();
  assert.equal(await tab.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await tab.getByRole('link', { name: 'Погода', exact: true }).click();
  await tab.locator('.weather-report').waitFor();
  await tab.locator('.forecast-hour').first().click();
  await tab.getByText('Влажный термометр', { exact: true }).waitFor();
  await tab.getByRole('button', { name: 'Закрыть', exact: true }).click();
  await safari.close();
  console.log('PASS: phone layouts, safe areas, five tabs, 3D camera/layers/full screen, eight environments, automatic monitoring, news, weather details, offline cache, API recovery, night rain, Safari/WebKit.');
})().catch(error => { console.error(error); process.exit(1); });
