const {chromium,webkit}=require('@playwright/test');
const assert=require('node:assert/strict');
const QRCode=require('qrcode');
const origin=process.env.EGIN_URL||'http://localhost:4935';
(async()=>{
 const browser=await chromium.launch({args:['--no-sandbox','--enable-unsafe-swiftshader']});
 const make=async()=>{const c=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});await c.route('https://api.open-meteo.com/**',r=>r.fulfill({json:require('./fixtures/open-meteo.json')}));await c.route('**/api/news',r=>r.fulfill({json:require('./fixtures/news.json')}));await c.route('https://eldala.kz/**',r=>r.abort());return c;};
 const phone=await make(),laptop=await make();const p=await phone.newPage(),l=await laptop.newPage();const errors=[];for(const page of [p,l])page.on('pageerror',e=>errors.push(e.message));
 const cdp=await phone.newCDPSession(p);await cdp.send('WebAuthn.enable');const {authenticatorId}=await cdp.send('WebAuthn.addVirtualAuthenticator',{options:{protocol:'ctap2',transport:'internal',hasResidentKey:true,hasUserVerification:true,isUserVerified:true,automaticPresenceSimulation:true}});
 await p.goto(origin+'/#/auth');await p.getByRole('button',{name:'Создать профиль',exact:true}).click();await p.getByLabel('Ваше имя').fill('Scanner test');const options=p.waitForResponse(r=>r.url().endsWith('/register/options'));await p.getByRole('button',{name:'Создать passkey',exact:true}).click();assert.equal((await(await options).json()).options.authenticatorSelection.authenticatorAttachment,'platform');await p.getByRole('button',{name:'Код сохранён',exact:true}).click();await p.getByRole('navigation').waitFor();
 const start=async()=>{await l.goto(origin+'/#/auth');await l.reload();const response=l.waitForResponse(r=>r.url().endsWith('/qr/start'));await l.getByRole('button',{name:'Войти по QR с телефона'}).click();const qr=await(await response).json();const img=l.getByAltText('QR для входа в EGIN');await img.waitFor();return {...qr,png:await img.screenshot()};};
 const first=await start();await p.goto(origin+'/#/auth/scan');await p.getByLabel('Изображение QR-кода').setInputFiles({name:'login.png',mimeType:'image/png',buffer:first.png});await p.getByText('Я начал этот вход, коды совпадают').waitFor();assert.equal(await p.locator('.auth-code').textContent(),first.code);await p.getByRole('checkbox').check();await p.getByRole('button',{name:'Подтвердить с passkey'}).click();await l.getByRole('navigation').waitFor({timeout:15000});
 await laptop.request.post(origin+'/api/logout',{headers:{'X-EGIN':'1'}});
 const second=await start();
 // A camera link opened in a fresh browser must retain its QR through passkey login.
 const fresh=await make(),f=await fresh.newPage();f.on('pageerror',e=>errors.push(e.message));const freshCDP=await fresh.newCDPSession(f);await freshCDP.send('WebAuthn.enable');const freshAuthenticator=await freshCDP.send('WebAuthn.addVirtualAuthenticator',{options:{protocol:'ctap2',transport:'internal',hasResidentKey:true,hasUserVerification:true,isUserVerified:true,automaticPresenceSimulation:true}});const {credentials}=await cdp.send('WebAuthn.getCredentials',{authenticatorId});for(const credential of credentials)await freshCDP.send('WebAuthn.addCredential',{authenticatorId:freshAuthenticator.authenticatorId,credential});
 await f.goto(second.url);await f.getByRole('button',{name:'Войти с ключом',exact:true}).waitFor();await f.getByRole('button',{name:'Войти с ключом',exact:true}).click();await f.getByText('Я начал этот вход, коды совпадают').waitFor();assert.equal(await f.locator('.auth-code').textContent(),second.code);assert.equal(await f.getByRole('button',{name:'Подтвердить с passkey'}).isDisabled(),true);
 // Simulate a signed-in phone whose old key is on another device.
 for(const credential of credentials)await freshCDP.send('WebAuthn.removeCredential',{authenticatorId:freshAuthenticator.authenticatorId,credentialId:credential.credentialId});
 // Add a key to this account without creating a second profile.
 const adding=f.waitForResponse(r=>r.url().endsWith('/register/verify'));await f.getByRole('button',{name:'Создать ключ на этом телефоне'}).click();assert.equal((await(await adding).json()).recovery,null);await f.getByText('Ключ добавлен. Теперь можно подтвердить вход.').waitFor();await f.getByRole('checkbox').check();await f.getByRole('button',{name:'Подтвердить с passkey'}).click();await l.getByRole('navigation').waitFor({timeout:15000});await laptop.request.post(origin+'/api/logout',{headers:{'X-EGIN':'1'}});
 const third=await start();await p.goto(origin+'/#/auth/scan');
 // Feed the actual site QR as live video; recognition runs through the production decoder.
 await p.evaluate(async png=>{const image=new Image();image.src='data:image/png;base64,'+png;await image.decode();navigator.mediaDevices.getUserMedia=async()=>{const canvas=document.createElement('canvas');canvas.width=1280;canvas.height=720;const ctx=canvas.getContext('2d');const draw=()=>{ctx.fillStyle='#eee';ctx.fillRect(0,0,1280,720);ctx.imageSmoothingEnabled=false;ctx.drawImage(image,420,140,440,440);};draw();const stream=canvas.captureStream(15);const timer=setInterval(draw,65);window.__scannerTracks=stream.getTracks();for(const track of stream.getTracks()){const stop=track.stop.bind(track);track.stop=()=>{clearInterval(timer);stop();};}return stream;};},third.png.toString('base64'));
 await p.getByRole('button',{name:'Сканировать QR',exact:true}).click();await p.getByText('Я начал этот вход, коды совпадают').waitFor();assert.equal(await p.locator('.auth-code').textContent(),third.code);assert.ok(await p.evaluate(()=>window.__scannerTracks.every(t=>t.readyState==='ended')));
 await p.getByRole('button',{name:'Отклонить вход'}).click();await p.getByText('Вход отклонён.',{exact:true}).waitFor();await l.getByRole('button',{name:'Создать новый QR'}).waitFor({timeout:15000});
 const fourth=await start();await p.goto(origin+'/#/settings/sensors');await p.getByRole('button',{name:'Добавить датчик',exact:true}).click();await p.getByLabel('Изображение QR-кода').setInputFiles({name:'login.png',mimeType:'image/png',buffer:fourth.png});await p.getByText('Я начал этот вход, коды совпадают').waitFor();assert.equal(await p.locator('.auth-code').textContent(),fourth.code);await p.getByRole('button',{name:'Отклонить вход'}).click();
 await p.goto(origin+'/#/auth/scan');await p.getByLabel('Изображение QR-кода').setInputFiles({name:'system.png',mimeType:'image/png',buffer:await QRCode.toBuffer('FIDO:/123456789')});await p.getByText(/Это системный QR для passkey/).waitFor();assert.ok(p.url().endsWith('/auth/scan'));assert.deepEqual(errors,[]);await browser.close();
 const safari=await webkit.launch();const page=await safari.newPage({viewport:{width:390,height:844},isMobile:true});await page.route('https://api.open-meteo.com/**',r=>r.fulfill({json:require('./fixtures/open-meteo.json')}));await page.goto(origin+'/#/auth/scan');await page.getByLabel('Изображение QR-кода').setInputFiles({name:'login.png',mimeType:'image/png',buffer:fourth.png});await page.getByRole('button',{name:'Войти с ключом',exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await safari.close();
 console.log('PASS: QR image and live camera decoding, camera shutdown, sensor-scanner login routing, system QR explanation, fresh-browser key login preserving QR, on-phone key creation, Safari image decoding.');
})().catch(e=>{console.error(e);process.exit(1)});
