const {chromium,webkit}=require('@playwright/test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const QRCode=require('qrcode');
const fixture=require('./fixtures/open-meteo.json');
const origin=process.env.EGIN_URL||'http://localhost:4935';
const path=require('node:path');
const root=path.resolve(__dirname,'../../..');
const out=path.join(root,'test-results/workspace');
(async()=>{
fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({args:['--no-sandbox','--enable-unsafe-swiftshader','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce',acceptDownloads:true,permissions:['geolocation','microphone','camera'],geolocation:{latitude:51.17,longitude:71.44,accuracy:10}});
await context.route('https://api.open-meteo.com/**',r=>r.fulfill({json:fixture}));
await context.route('https://tile.openstreetmap.org/**',r=>r.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aJz4AAAAASUVORK5CYII=','base64')}));
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
page.setDefaultTimeout(20000);
const cdp=await context.newCDPSession(page);await cdp.send('WebAuthn.enable');const {authenticatorId}=await cdp.send('WebAuthn.addVirtualAuthenticator',{options:{protocol:'ctap2',transport:'internal',hasResidentKey:true,hasUserVerification:true,isUserVerified:true,automaticPresenceSimulation:true}});
await page.goto(origin+'/#/settings');
await page.getByRole('heading',{name:'Настройки',exact:true}).waitFor();
await page.screenshot({path:out+'/settings.png',fullPage:true});
for(const width of [320,360,390,430]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
await page.setViewportSize({width:390,height:844});
await page.getByRole('link',{name:/Мои участки Карта/}).click();
await page.getByRole('button',{name:'Добавить участок',exact:true}).last().click();
await page.getByLabel('Название',{exact:true}).fill('Тестовое поле');
await page.getByRole('button',{name:'Моё местоположение',exact:true}).click();
await page.getByText(/Точность местоположения/).waitFor();
await page.getByLabel('Площадь, га').fill('12.5');
await page.getByRole('button',{name:'Сохранить участок',exact:true}).click();
await page.getByRole('heading',{name:'Тестовое поле',exact:true}).waitFor();
await page.goto(origin+'/#/journal');
await page.getByRole('button',{name:'Новая запись',exact:true}).click();
await page.getByLabel('Заголовок',{exact:true}).fill('Осмотр после дождя');
await page.getByLabel('Наблюдения',{exact:true}).fill('Листья чистые. Проверить через два дня.');
await page.screenshot({path:out+'/editor.png'});
await page.getByRole('dialog').locator('select').selectOption({label:'Тестовое поле'});
await page.getByLabel('Добавить фото',{exact:true}).setInputFiles(path.resolve(__dirname,'../public/icons/icon-192.png'));
await page.locator('.entry-photo').waitFor();
await page.getByRole('button',{name:'Голосовая заметка',exact:true}).click();
await page.getByRole('button',{name:/Остановить ·/}).waitFor();
await page.waitForTimeout(500);
await page.getByRole('button',{name:/Остановить ·/}).click();
await page.locator('audio').waitFor();
await page.getByRole('button',{name:'Сохранить запись',exact:true}).click();
await page.getByRole('heading',{name:'Осмотр после дождя',exact:true}).waitFor();
await page.reload();
await page.getByRole('heading',{name:'Осмотр после дождя',exact:true}).waitFor();
await page.goto(origin+'/#/settings/profile');
await page.getByLabel('Имя',{exact:true}).fill('Проверка EGIN');
await page.getByRole('button',{name:'Создать профиль с passkey',exact:true}).click();
await page.getByRole('heading',{name:'Сохраните код восстановления',exact:true}).waitFor();
const recovery=await page.locator('.recovery-card code').textContent();assert.ok(recovery.length>20);
await page.getByRole('button',{name:'Код сохранён',exact:true}).click();
await page.goto(origin+'/#/settings/sync');
await page.getByRole('button',{name:'Синхронизировать сейчас',exact:true}).click();
await page.getByText('Все записи синхронизированы',{exact:true}).waitFor();
const apiRecords=await page.evaluate(()=>fetch('/api/sync').then(r=>r.json()));
assert.equal(apiRecords.records.filter(r=>r.kind==='entry').length,1);
assert.equal(apiRecords.records.find(r=>r.kind==='entry').data.assets.length,2);
await page.goto(origin+'/#/settings/sensors');
await page.getByRole('button',{name:'Добавить датчик',exact:true}).click();
await page.getByText('Вставить содержимое QR',{exact:true}).click();
await page.getByLabel('Код',{exact:true}).fill('https://evil.example/');
await page.getByRole('button',{name:'Прочитать код',exact:true}).click();
await page.screenshot({path:out+'/qr-debug.png'});
await page.getByText('Это не QR датчика EGIN. Используйте ручной ввод.',{exact:true}).waitFor();
await page.getByLabel('Изображение QR-кода',{exact:true}).setInputFiles({name:'sensor.png',mimeType:'image/png',buffer:await QRCode.toBuffer('egin://sensor?id=SOIL-001&type=moisture&name=Soil')});
await page.waitForFunction(()=>document.querySelector('input[pattern]')?.value==='SOIL-001');
assert.equal(await page.getByLabel('Серийный номер',{exact:true}).inputValue(),'SOIL-001');
await page.getByRole('button',{name:'Сохранить датчик',exact:true}).click();
await page.getByText('Ожидает подключения API',{exact:true}).waitFor();
await page.goto(origin+'/#/settings/reports');
await page.getByRole('button',{name:'Сформировать отчёт',exact:true}).click();
await page.getByRole('button',{name:'Скачать файл',exact:true}).waitFor();
const reportPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Скачать файл',exact:true}).click();const report=await reportPromise;await report.saveAs(out+'/report.html');const html=fs.readFileSync(out+'/report.html','utf8');assert.ok(html.includes('Осмотр после дождя')&&html.includes('data:image/jpeg')&&html.includes('data:audio/'));
await page.getByLabel('Формат',{exact:true}).selectOption('csv');await page.getByRole('button',{name:'Сформировать отчёт',exact:true}).click();assert.ok(await page.getByRole('button',{name:'Поделиться',exact:true}).isVisible());
await page.goto(origin+'/#/journal');
await page.evaluate(()=>Promise.race([navigator.serviceWorker.ready.then(()=>true),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Service worker activation timed out')),20000))]));await page.reload();await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
await context.setOffline(true);await page.reload();
await page.getByRole('button',{name:'Новая запись',exact:true}).click();await page.getByLabel('Заголовок',{exact:true}).fill('Запись без сети');await page.getByRole('button',{name:'Сохранить запись',exact:true}).click();await page.reload();await page.getByRole('heading',{name:'Запись без сети',exact:true}).waitFor();
await context.setOffline(false);await page.goto(origin+'/#/settings/sync');await page.getByRole('button',{name:'Синхронизировать сейчас',exact:true}).click();await page.getByText('Все записи синхронизированы',{exact:true}).waitFor();
assert.equal((await page.evaluate(()=>fetch('/api/sync').then(r=>r.json()))).records.filter(r=>r.kind==='entry').length,2);
// A separate browser context is a separate device; authenticate with the resident credential.
const credentials=(await cdp.send('WebAuthn.getCredentials',{authenticatorId})).credentials;
const second=await browser.newContext({viewport:{width:320,height:740},isMobile:true,hasTouch:true,reducedMotion:'reduce'});await second.route('https://api.open-meteo.com/**',r=>r.fulfill({json:fixture}));const p2=await second.newPage();p2.setDefaultTimeout(20000);const dev2=await second.newCDPSession(p2);await dev2.send('WebAuthn.enable');const a2=await dev2.send('WebAuthn.addVirtualAuthenticator',{options:{protocol:'ctap2',transport:'internal',hasResidentKey:true,hasUserVerification:true,isUserVerified:true,automaticPresenceSimulation:true}});for(const credential of credentials)await dev2.send('WebAuthn.addCredential',{authenticatorId:a2.authenticatorId,credential});
await p2.goto(origin+'/#/settings/profile');await p2.getByRole('button',{name:'Войти с passkey',exact:true}).click();await p2.getByRole('link',{name:/Безопасность и вход/}).waitFor();await p2.goto(origin+'/#/journal');await p2.getByRole('heading',{name:'Осмотр после дождя',exact:true}).waitFor();await p2.getByRole('button',{name:/Осмотр после дождя/}).click();await p2.locator('.entry-photo').waitFor();assert.equal(await p2.locator('audio').count(),1);await p2.keyboard.press('Escape');
// Create divergent offline edits on two devices, then expose both versions.
await page.goto(origin+'/#/journal');await context.setOffline(true);await page.getByRole('button',{name:/Осмотр после дождя/}).click();await page.waitForTimeout(250);await page.screenshot({path:out+'/conflict-debug.png'});await page.getByLabel('Наблюдения',{exact:true}).fill('Изменено на первом телефоне');await page.getByRole('button',{name:'Сохранить запись',exact:true}).click();
await p2.getByRole('button',{name:/Осмотр после дождя/}).click();await p2.getByLabel('Наблюдения',{exact:true}).fill('Изменено на втором телефоне');await p2.getByRole('button',{name:'Сохранить запись',exact:true}).click();await p2.goto(origin+'/#/settings/sync');await p2.getByRole('button',{name:'Синхронизировать сейчас',exact:true}).click();await p2.getByText('Все записи синхронизированы',{exact:true}).waitFor();
await context.setOffline(false);await page.goto(origin+'/#/settings/sync');await page.getByRole('button',{name:'Синхронизировать сейчас',exact:true}).click();await page.getByRole('heading',{name:'Разные версии записи',exact:true}).waitFor();await page.getByRole('button',{name:'Принять версию сервера',exact:true}).click();await page.locator('.conflict-card').waitFor({state:'detached'});
await page.goto(origin+'/#/settings/security');await page.getByRole('button',{name:'Добавить passkey',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Удалить ключ',exact:true}).isDisabled(),true);
assert.deepEqual(errors,[]);
await page.goto(origin+'/#/journal');await page.screenshot({path:out+'/journal.png'});
await context.close();await second.close();await browser.close();
const safari=await webkit.launch();const ios=await safari.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true,reducedMotion:'reduce'});await ios.route('https://api.open-meteo.com/**',r=>r.fulfill({json:fixture}));const tab=await ios.newPage();await tab.goto(origin+'/#/journal');await tab.getByRole('button',{name:'Новая запись',exact:true}).click();await tab.getByLabel('Заголовок',{exact:true}).fill('Safari offline');await tab.getByRole('button',{name:'Сохранить запись',exact:true}).click();await tab.reload();await tab.getByRole('heading',{name:'Safari offline',exact:true}).waitFor();assert.equal(await tab.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await safari.close();
console.log('PASS: settings, map/geolocation, offline diary/photo/audio, real passkey registration/login, account sync and isolation, second-device media, conflict resolution, sensors/QR validation, HTML/CSV export, Safari persistence.');
})().catch(e=>{console.error(e);process.exit(1)});
